#
# PRODUCTION
#
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: #DB_NAME#
  pool: 10
  username: #DB_USER#
  password: #DB_PASS#
  host: #DB_HOST#
  # socket: /tmp/mysql.sock
